canton {
  participants {
    my-participant {
      storage {
        type = memory
      }
      admin-api {
        port = 5012
        address = "0.0.0.0"
      }
      ledger-api {
        port = 5011
        address = "0.0.0.0"
      }
      http-ledger-api {
		port = 5013
		address = "0.0.0.0"
	}
    }
  }
  sequencers {
    my-sequencer {
      storage {
        type = memory
      }
      public-api {
        port = 5018
        address = "0.0.0.0"
      }
      admin-api {
        port = 5019
        address = "0.0.0.0"
      }
    }
  }
  mediators {
    my-mediator {
      storage {
        type = memory
      }
      admin-api {
        port = 5020
        address = "0.0.0.0"
      }
    }
  }
}