canton {
  participant {
    participants {
      participant1 {
        storage = memory
        ledger-api { address = "0.0.0.0", port = 6865 }
      }
    }
  }
  domains {
    domain1 {
      storage = memory
      public { address = "0.0.0.0", port = 5012 }
    }
  }
}
